remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme
title: Resources for Makers
description: For Makers, Creators, Engineers, Designers, and students who want to build cool things.
markdown: kramdown

include:
  - /MakerspaceatUH/
  - /RoboticsatUH/
  - /ESIDEatCullen/
  - /Classwork/
  - /Pages/

